apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pos-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pos-frontend.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
