{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "pos-frontend.fullname" . }}-gateway
  labels:
    {{- include "pos-frontend.labels" . | nindent 4 }}
  {{- with .Values.istio.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
  {{- range .Values.istio.gateway.servers }}
  - port:
      number: {{ .port.number }}
      name: {{ .port.name }}
      protocol: {{ .port.protocol }}
    hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .tls }}
    tls:
      {{- toYaml .tls | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
