{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pos-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pos-frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pos-frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
      - protocol: UDP
        port: 53
    # Allow HTTPS outbound (for external APIs if needed)
    - to: []
      ports:
      - protocol: TCP
        port: 443
    # Allow HTTP outbound (for external APIs if needed)
    - to: []
      ports:
      - protocol: TCP
        port: 80
{{- end }}
