{{- if and .Values.istio.enabled (or .Values.monitoring.serviceMonitor.enabled .Values.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pos-frontend.fullname" . }}-monitor
  labels:
    {{- include "pos-frontend.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pos-frontend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.portName | default "http" }}
    path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
    {{- if .Values.monitoring.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.monitoring.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.monitoring.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
{{- end }}
